export const GET_STARS = 'GET_STARS';
export const GET_STARS_SUCCESS = 'GET_STARS_SUCCESS';
export const GET_STARS_FAILURE = 'GET_STARS_FAILURE';

export const UPDATE_VIEW = 'UPDATE_VIEW';
export const UPDATE_EYEPIECE_VIEW = 'UPDATE_EYEPIECE_VIEW';
