export const GET_STARS = 'GET_STARS';
export const GET_STARS_SUCCESS = 'GET_STARS_SUCCESS';
export const GET_STARS_FAILURE = 'GET_STARS_FAILURE';

export const GET_DEEP_SPACE = 'GET_DEEP_SPACE';
export const GET_DEEP_SPACE_SUCCESS = 'GET_DEEP_SPACE_SUCCESS';
export const GET_DEEP_SPACE_FAILURE = 'GET_DEEP_SPACE_FAILURE';

export const UPDATE_HINTS = 'UPDATE_HINTS';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_VIEW = 'UPDATE_VIEW';
export const UPDATE_EYEPIECE_VIEW = 'UPDATE_EYEPIECE_VIEW';

export const UPDATE_SELECTED_HOP = 'UPDATE_SELECTED_HOP';
export const UPDATE_SKY_DARKNESS = 'UPDATE_SKY_DARKNESS';
